### ISSUE TITLE
Getting error "each arg must be a type. Got Ellipsis"

### ISSUE THREAD

**Issue by MonoS** [YomikoR/VapourSynth-Destripe#2]
```
Failed to evaluate the script:
Python exception: Callable[[arg, ...], result]: each arg must be a type. Got Ellipsis.

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript
File "***.vpy", line 5, in 
from destripe import Destripe
File "C:\Program Files\Python38\lib\site-packages\destripe.py", line 95, in 
taps: int) -> Callable[[vs.VideoNode, int, int, ...], vs.VideoNode]:
File "C:\Program Files\Python38\Lib\typing.py", line 813, in __getitem__
return self.__getitem_inner__(params)
File "C:\Program Files\Python38\Lib\typing.py", line 261, in inner
return func(*args, **kwds)
File "C:\Program Files\Python38\Lib\typing.py", line 836, in __getitem_inner__
args = tuple(_type_check(arg, msg) for arg in args)
File "C:\Program Files\Python38\Lib\typing.py", line 836, in 
args = tuple(_type_check(arg, msg) for arg in args)
File "C:\Program Files\Python38\Lib\typing.py", line 149, in _type_check
raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Callable[[arg, ...], result]: each arg must be a type. Got Ellipsis.
```

**Comment by YomikoR** [comment]
Sorry, I'm too dumb for the typing stuff. It seems Python 3.9 accepts them, so I may not make changes until I understand there's a good way. You can drop the `-> Callable[...` suffixes from line 95 and line 114 if they make troubles.

**Comment by MonoS** [comment]
I've update both VS and Python to 3.9.x version and, as you suggested, it works, i'll put this requirement in the readme.
